/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbo1a223303;

import com.sun.corba.se.impl.orbutil.CorbaResourceUtil;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import java.util.Scanner;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author wildan
 */
public class frm_latih5 extends javax.swing.JFrame {

    /**
     * Creates new form frm_latih5
     */
    public frm_latih5() {
        initComponents();
    }
    void filterhuruf(KeyEvent a){
        if (Character.isAlphabetic(a.getKeyChar())){
            a.consume();
            JOptionPane.showMessageDialog(null, "Inputan Hanya angka saja..","Peringatan",1);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtNIM = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtProdi = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtSkstotal = new javax.swing.JTextField();
        txtIPS = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        cmbMatkul = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelMatkul = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        txtSKS = new javax.swing.JTextField();
        txtJenis = new javax.swing.JTextField();
        txtTugas = new javax.swing.JTextField();
        txtUTS = new javax.swing.JTextField();
        txtUAS = new javax.swing.JTextField();
        txtAkhir = new javax.swing.JTextField();
        txtHuruf = new javax.swing.JTextField();
        btnBaru = new javax.swing.JButton();
        btnBersih = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NIM");

        txtNIM.setEnabled(false);
        txtNIM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNIMFocusLost(evt);
            }
        });
        txtNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIMActionPerformed(evt);
            }
        });

        jLabel2.setText("Program Studi");

        jLabel3.setText("Nama");

        jLabel4.setText("SKS Total");

        jLabel5.setText("IPS");

        txtProdi.setEnabled(false);
        txtProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdiActionPerformed(evt);
            }
        });

        txtNama.setEnabled(false);
        txtNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNamaFocusLost(evt);
            }
        });
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        txtSkstotal.setEnabled(false);
        txtSkstotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSkstotalActionPerformed(evt);
            }
        });

        txtIPS.setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setEnabled(false);

        jLabel6.setText("Mata Kuliah");

        jLabel7.setText("SKS");

        jLabel8.setText("Jenis");

        jLabel9.setText("Tugas");

        jLabel10.setText("UTS");

        jLabel11.setText("UAS");

        jLabel12.setText("Akhir");

        jLabel13.setText("Huruf");

        btnTambah.setText("Tambah");
        btnTambah.setEnabled(false);
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        cmbMatkul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Mata Kuliah", "Pemrograman GIS", "Basis Data Lanjut", "Pemrograman Mobile 1", "PBO 1", "Bahasa Inggris" }));
        cmbMatkul.setEnabled(false);
        cmbMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMatkulActionPerformed(evt);
            }
        });

        tabelMatkul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mata Kuliah", "SKS", "Jenis", "Tugas", "UTS", "UAS", "Akhir", "Huruf"
            }
        ));
        jScrollPane2.setViewportView(tabelMatkul);

        btnHapus.setText("Hapus");
        btnHapus.setEnabled(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        txtSKS.setEnabled(false);

        txtJenis.setEnabled(false);

        txtTugas.setEnabled(false);
        txtTugas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTugasFocusLost(evt);
            }
        });
        txtTugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTugasActionPerformed(evt);
            }
        });
        txtTugas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTugasKeyTyped(evt);
            }
        });

        txtUTS.setEnabled(false);
        txtUTS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUTSFocusLost(evt);
            }
        });
        txtUTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUTSActionPerformed(evt);
            }
        });
        txtUTS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUTSKeyTyped(evt);
            }
        });

        txtUAS.setEnabled(false);
        txtUAS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUASFocusLost(evt);
            }
        });
        txtUAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUASActionPerformed(evt);
            }
        });
        txtUAS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUASKeyTyped(evt);
            }
        });

        txtAkhir.setEnabled(false);

        txtHuruf.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel6)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel7)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(cmbMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSKS, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel11)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel12)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtUTS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtUAS, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtHuruf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTambah))
                    .addComponent(jLabel13))
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnHapus)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah)
                    .addComponent(txtTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHuruf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHapus)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        btnBaru.setText("Baru");
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });

        btnBersih.setText("Bersih");
        btnBersih.setEnabled(false);
        btnBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.setEnabled(false);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnBaru)
                .addGap(18, 18, 18)
                .addComponent(btnBersih)
                .addGap(18, 18, 18)
                .addComponent(btnBatal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 306, Short.MAX_VALUE)
                .addComponent(btnKeluar)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNIM, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(txtProdi)
                            .addComponent(txtNama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSkstotal)
                            .addComponent(txtIPS, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtSkstotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txtProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaru)
                    .addComponent(btnBersih)
                    .addComponent(btnBatal)
                    .addComponent(btnKeluar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIMActionPerformed
        String nmprogdi = null, progdi = txtNIM.getText().substring(0,3);
        int pilih;
        if (progdi.equalsIgnoreCase("A22")) {
            nmprogdi="TI - D3";
            pilih=1;
        }else if (progdi.equalsIgnoreCase("A24")) {
            nmprogdi = "Broadcasting - D3";
            pilih = 1;
        }else{
            txtNama.setEnabled(false);
            JOptionPane.showMessageDialog(null, "NIM salah, ulangi ...", "peringatan", 1);
            pilih =0;
            txtNIM.requestFocus();
        }
        if (pilih==1) {
            txtProdi.setText(nmprogdi);
            txtNama.setEnabled(true);
            txtNama.requestFocus();
        }
        btnBersih.setEnabled(true);
        btnBatal.setEnabled(true);
        btnBaru.setEnabled(false);
    }//GEN-LAST:event_txtNIMActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void txtProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdiActionPerformed
        
    }//GEN-LAST:event_txtProdiActionPerformed

    private void btnBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihActionPerformed
        txtNIM.setText("");
        txtNama.setText("");
        txtProdi.setText("");
        cmbMatkul.setSelectedItem("-- Pilih Mata Kuliah");
        txtSKS.setText("");
        txtJenis.setText("");
        txtTugas.setText("");
        txtUTS.setText("");
        txtUAS.setText("");
        txtAkhir.setText("");
        txtHuruf.setText("");
        txtSkstotal.setText("");
        txtIPS.setText("");
        DefaultTableModel dataModel = (DefaultTableModel) tabelMatkul.getModel();
        if (tabelMatkul.getRowCount()>0) {
            for (int i = tabelMatkul.getRowCount()-1; i > -1; i--) {
                dataModel.removeRow(i);
            }
        }
        txtNIM.setEnabled(true);
        txtNama.setEnabled(false);
        txtProdi.setEnabled(false);
        cmbMatkul.setEnabled(false);
        txtTugas.setEnabled(false);
        txtUTS.setEnabled(false);
        txtUAS.setEnabled(false);
        btnTambah.setEnabled(false);
        btnHapus.setEnabled(false);
        btnBatal.setEnabled(true);
        btnBaru.setEnabled(false);
        txtNIM.requestFocus();
    }//GEN-LAST:event_btnBersihActionPerformed

    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed
        txtNIM.setEnabled(true);
        txtNIM.requestFocus();
    }//GEN-LAST:event_btnBaruActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        cmbMatkul.setEnabled(true);
    }//GEN-LAST:event_txtNamaActionPerformed

    private void cmbMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMatkulActionPerformed
        if(cmbMatkul.getSelectedItem()=="-- Pilih Mata Kuliah"){
            txtSKS.setText("");
            txtJenis.setText("");
            txtTugas.setText("");
            txtUTS.setText("");
            txtUAS.setText("");
            txtAkhir.setText("");
            txtHuruf.setText("");
            txtTugas.setEnabled(false);
            txtUTS.setEnabled(false);
            txtUAS.setEnabled(false);
            btnTambah.setEnabled(false);
            cmbMatkul.requestFocus();
        }else if(cmbMatkul.getSelectedItem()=="Pemrograman GIS"){
            txtSKS.setText("4");
            txtJenis.setText("P");
            txtTugas.setText("");
            txtUTS.setText("");
            txtUAS.setText("");
            txtAkhir.setText("");
            txtHuruf.setText("");
            txtTugas.setEnabled(true);
            txtUTS.setEnabled(true);
            txtUAS.setEnabled(true);
            btnTambah.setEnabled(false);
            txtTugas.requestFocus();
        }else if(cmbMatkul.getSelectedItem()=="Basis Data Lanjut"){
            txtSKS.setText("4");
            txtJenis.setText("P/T");
            txtTugas.setText("");
            txtUTS.setText("");
            txtUAS.setText("");
            txtAkhir.setText("");
            txtHuruf.setText("");
            txtTugas.setEnabled(true);
            txtUTS.setEnabled(true);
            txtUAS.setEnabled(true);
            btnTambah.setEnabled(false);
            txtTugas.requestFocus();
        }else if(cmbMatkul.getSelectedItem()=="Pemrograman Mobile 1"){
            txtSKS.setText("4");
            txtJenis.setText("P");
            txtTugas.setText("");
            txtUTS.setText("");
            txtUAS.setText("");
            txtAkhir.setText("");
            txtHuruf.setText("");
            txtTugas.setEnabled(true);
            txtUTS.setEnabled(true);
            txtUAS.setEnabled(true);
            btnTambah.setEnabled(false);
            txtTugas.requestFocus();
        }else if(cmbMatkul.getSelectedItem()=="PBO 1"){
            txtSKS.setText("4");
            txtJenis.setText("P");
            txtTugas.setText("");
            txtUTS.setText("");
            txtUAS.setText("");
            txtAkhir.setText("");
            txtHuruf.setText("");
            txtTugas.setEnabled(true);
            txtUTS.setEnabled(true);
            txtUAS.setEnabled(true);
            btnTambah.setEnabled(false);
            txtTugas.requestFocus();
        }else if(cmbMatkul.getSelectedItem()=="Bahasa Inggris"){
            txtSKS.setText("2");
            txtJenis.setText("T");
            txtTugas.setText("");
            txtUTS.setText("");
            txtUAS.setText("");
            txtAkhir.setText("");
            txtHuruf.setText("");
            txtTugas.setEnabled(true);
            txtUTS.setEnabled(true);
            txtUAS.setEnabled(true);
            btnTambah.setEnabled(false);
            txtTugas.requestFocus();
        }
    }//GEN-LAST:event_cmbMatkulActionPerformed

    private void txtTugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTugasActionPerformed
        int tugas, uts, uas;
        double akhir;
        String huruf;
        
        //cek validasi
        if (txtTugas.getText().isEmpty()) {
            tugas=0;
        }else{
            tugas=Integer.parseInt(txtTugas.getText());
        }
        if(txtUTS.getText().isEmpty()){
            uts=0;
        }else{
            uts=Integer.parseInt(txtUTS.getText());
        }
        if(txtUAS.getText().isEmpty()){
            uas=0;
        }else{
            uas=Integer.parseInt(txtUAS.getText());
        }
        akhir=(0.2*tugas)+(0.3*uts)+(0.5*uas);
        txtAkhir.setText(String.valueOf(akhir));
        if (akhir>=85) {
            huruf="A";
        }else if(akhir>=80){
            huruf="AB";
        }else if(akhir>=70){
            huruf="B";
        }else if(akhir>=65){
            huruf="BC";
        }else if(akhir>=60){
            huruf="C";
        }else if(akhir>=50){
            huruf="D";
        }else{
            huruf="E";
        }
        txtHuruf.setText(huruf);
        txtUTS.requestFocus();
    }//GEN-LAST:event_txtTugasActionPerformed

    private void txtUASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUASActionPerformed
        int tugas, uts, uas;
        double akhir;
        String huruf;
        
        //cek validasi
        if (txtTugas.getText().isEmpty()) {
            tugas=0;
        }else{
            tugas=Integer.parseInt(txtTugas.getText());
        }
        if(txtUTS.getText().isEmpty()){
            uts=0;
        }else{
            uts=Integer.parseInt(txtUTS.getText());
        }
        if(txtUAS.getText().isEmpty()){
            uas=0;
        }else{
            uas=Integer.parseInt(txtUAS.getText());
        }
        akhir=(0.2*tugas)+(0.3*uts)+(0.5*uas);
        txtAkhir.setText(String.valueOf(akhir));
        if (akhir>=85) {
            huruf="A";
        }else if(akhir>=80){
            huruf="AB";
        }else if(akhir>=70){
            huruf="B";
        }else if(akhir>=65){
            huruf="BC";
        }else if(akhir>=60){
            huruf="C";
        }else if(akhir>=50){
            huruf="D";
        }else{
            huruf="E";
        }
        txtHuruf.setText(huruf);
        btnTambah.setEnabled(true);
    }//GEN-LAST:event_txtUASActionPerformed

    private void txtUTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUTSActionPerformed
        int tugas, uts, uas;
        double akhir;
        String huruf;
        
        //cek validasi
        if (txtTugas.getText().isEmpty()) {
            tugas=0;
        }else{
            tugas=Integer.parseInt(txtTugas.getText());
        }
        if(txtUTS.getText().isEmpty()){
            uts=0;
        }else{
            uts=Integer.parseInt(txtUTS.getText());
        }
        if(txtUAS.getText().isEmpty()){
            uas=0;
        }else{
            uas=Integer.parseInt(txtUAS.getText());
        }
        akhir=(0.2*tugas)+(0.3*uts)+(0.5*uas);
        txtAkhir.setText(String.valueOf(akhir));
        if (akhir>=85) {
            huruf="A";
        }else if(akhir>=80){
            huruf="AB";
        }else if(akhir>=70){
            huruf="B";
        }else if(akhir>=65){
            huruf="BC";
        }else if(akhir>=60){
            huruf="C";
        }else if(akhir>=50){
            huruf="D";
        }else{
            huruf="E";
        }
        txtHuruf.setText(huruf);
        txtUAS.requestFocus();
    }//GEN-LAST:event_txtUTSActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        DefaultTableModel dataModel = (DefaultTableModel) tabelMatkul.getModel();
        List list = new ArrayList<>();
        tabelMatkul.setAutoCreateColumnsFromModel(true);
        list.add(cmbMatkul.getSelectedItem());
        list.add(txtSKS.getText());
        list.add(txtJenis.getText());
        list.add(txtTugas.getText());
        list.add(txtUTS.getText());
        list.add(txtUAS.getText());
        list.add(txtAkhir.getText());
        list.add(txtHuruf.getText());
        dataModel.addRow(list.toArray());
        double bobot, bobotsks=0, bobottotal=0, ips, skstotal=0, sks;
        String huruf;
        int jmlbaris = dataModel.getRowCount();
        for (int i = 0; i < jmlbaris; i++) {
            sks=Integer.valueOf(dataModel.getValueAt(i, 1).toString());
            skstotal=skstotal+sks;
            //menghitung ips
            huruf=dataModel.getValueAt(i,7).toString();
            if (huruf.equals("A")) {
                bobot=4.0;
            }else if (huruf.equals("AB")) {
                bobot=3.5;
            }else if (huruf.equals("B")) {
                bobot=3.0;
            }else if (huruf.equals("BC")) {
                bobot=2.5;
            }else if (huruf.equals("C")) {
                bobot=2.0;
            }else if (huruf.equals("D")) {
                bobot=1.0;
            }else{
                bobot=0.0;
            }
            bobotsks=bobot*sks;
            bobottotal=bobottotal+bobotsks;
        }
        txtSkstotal.setText(String.valueOf(skstotal));
        ips=bobottotal/skstotal;
        txtIPS.setText(String.valueOf(ips));
        txtSKS.setText("");
        txtJenis.setText("");
        txtTugas.setText("");
        txtUTS.setText("");
        txtUAS.setText("");
        txtAkhir.setText("");
        txtHuruf.setText("");
        txtTugas.setEnabled(false);
        txtUTS.setEnabled(false);
        txtUAS.setEnabled(false);
        btnTambah.setEnabled(false);
        cmbMatkul.requestFocus();
        btnHapus.setEnabled(true);
        btnBatal.setEnabled(true);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void txtTugasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTugasKeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_txtTugasKeyTyped

    private void txtUTSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUTSKeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_txtUTSKeyTyped

    private void txtUASKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUASKeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_txtUASKeyTyped

    private void txtSkstotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSkstotalActionPerformed
        
    }//GEN-LAST:event_txtSkstotalActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        double bobot , bobotsks=0, bobottotal=0, ips;
        int brs=0 ,sks=0, skstotal = 0;
        String huruf;
        DefaultTableModel dataModel = (DefaultTableModel) tabelMatkul.getModel();
        brs=tabelMatkul.getSelectedRow();
        if(brs>=0){
            int opsi=JOptionPane.showConfirmDialog(null, "Yakin Dihapus ?", "Peringatan", JOptionPane.YES_NO_OPTION);
            if (opsi==JOptionPane.YES_OPTION){
                dataModel.removeRow(brs);
                int jmlbaris = dataModel.getRowCount();
                if (jmlbaris<=0){
                    txtSkstotal.setText("");
                    txtIPS.setText("");
                }else {
                    for (int i= 0; i <jmlbaris ; i++){
                        // menghitung SKS
                        sks = Integer.valueOf(dataModel.getValueAt(i, 1).toString());
                        skstotal = skstotal+sks;
                        // menghitung IPS
                        huruf = dataModel.getValueAt(i, 7).toString();
                        if(huruf.equals("A")){
                            bobot = 4.0;
                        }else if(huruf.equals("AB")){
                            bobot = 3.5;
                        }else if(huruf.equals("B")){
                            bobot = 3.0;
                        }else if(huruf.equals("BC")){
                            bobot = 2.5;
                        }else if(huruf.equals("C")){
                            bobot = 2.0;
                        }else if(huruf.equals("D")){
                            bobot = 1.0;
                        }else{
                            bobot = 0.0;
                        }
                        bobotsks = bobot*sks;
                        bobottotal = bobottotal + bobotsks;
                    }
                    txtSkstotal.setText(String.valueOf(skstotal));
                    ips= bobottotal / skstotal;
                    txtIPS.setText(String.valueOf(ips));
                    // Clear
                    txtSKS.setText("");
                    txtJenis.setText("");
                    txtTugas.setText("");
                    txtUTS.setText("");
                    txtUAS.setText("");
                    txtAkhir.setText("");
                    txtHuruf.setText("");
                    txtTugas.setEnabled(false);
                    txtUTS.setEnabled(false);
                    txtUAS.setEnabled(false);
                    btnTambah.setEnabled(false);
                    btnHapus.setEnabled(true);
                    btnBatal.setEnabled(true);
                    cmbMatkul.setSelectedIndex(0);
                    cmbMatkul.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        txtNIM.setText("");
        txtNama.setText("");
        txtProdi.setText("");
        cmbMatkul.setSelectedItem("-- Pilih Mata Kuliah");
        txtSKS.setText("");
        txtJenis.setText("");
        txtTugas.setText("");
        txtUTS.setText("");
        txtUAS.setText("");
        txtAkhir.setText("");
        txtHuruf.setText("");
        txtSkstotal.setText("");
        txtIPS.setText("");
        DefaultTableModel dataModel = (DefaultTableModel) tabelMatkul.getModel();
        if (tabelMatkul.getRowCount()>0) {
            for (int i = tabelMatkul.getRowCount()-1; i > -1; i--) {
                dataModel.removeRow(i);
            }
        }
        txtNIM.setEnabled(false);
        txtNama.setEnabled(false);
        txtProdi.setEnabled(false);
        cmbMatkul.setEnabled(false);
        txtTugas.setEnabled(false);
        txtUTS.setEnabled(false);
        txtUAS.setEnabled(false);
        btnTambah.setEnabled(false);
        btnHapus.setEnabled(false);
        btnBatal.setEnabled(false);
        btnBersih.setEnabled(false);
        btnBaru.setEnabled(true);
    }//GEN-LAST:event_btnBatalActionPerformed

    private void txtTugasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTugasFocusLost
        int tugas, uts, uas;
        double akhir;
        String huruf;
        
        //cek validasi
        if (txtTugas.getText().isEmpty()) {
            tugas=0;
        }else{
            tugas=Integer.parseInt(txtTugas.getText());
        }
        if(txtUTS.getText().isEmpty()){
            uts=0;
        }else{
            uts=Integer.parseInt(txtUTS.getText());
        }
        if(txtUAS.getText().isEmpty()){
            uas=0;
        }else{
            uas=Integer.parseInt(txtUAS.getText());
        }
        akhir=(0.2*tugas)+(0.3*uts)+(0.5*uas);
        txtAkhir.setText(String.valueOf(akhir));
        if (akhir>=85) {
            huruf="A";
        }else if(akhir>=80){
            huruf="AB";
        }else if(akhir>=70){
            huruf="B";
        }else if(akhir>=65){
            huruf="BC";
        }else if(akhir>=60){
            huruf="C";
        }else if(akhir>=50){
            huruf="D";
        }else{
            huruf="E";
        }
        txtHuruf.setText(huruf);
        txtUTS.requestFocus();
    }//GEN-LAST:event_txtTugasFocusLost

    private void txtUTSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUTSFocusLost
        int tugas, uts, uas;
        double akhir;
        String huruf;
        
        //cek validasi
        if (txtTugas.getText().isEmpty()) {
            tugas=0;
        }else{
            tugas=Integer.parseInt(txtTugas.getText());
        }
        if(txtUTS.getText().isEmpty()){
            uts=0;
        }else{
            uts=Integer.parseInt(txtUTS.getText());
        }
        if(txtUAS.getText().isEmpty()){
            uas=0;
        }else{
            uas=Integer.parseInt(txtUAS.getText());
        }
        akhir=(0.2*tugas)+(0.3*uts)+(0.5*uas);
        txtAkhir.setText(String.valueOf(akhir));
        if (akhir>=85) {
            huruf="A";
        }else if(akhir>=80){
            huruf="AB";
        }else if(akhir>=70){
            huruf="B";
        }else if(akhir>=65){
            huruf="BC";
        }else if(akhir>=60){
            huruf="C";
        }else if(akhir>=50){
            huruf="D";
        }else{
            huruf="E";
        }
        txtHuruf.setText(huruf);
        txtUAS.requestFocus();
    }//GEN-LAST:event_txtUTSFocusLost

    private void txtUASFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUASFocusLost
        int tugas, uts, uas;
        double akhir;
        String huruf;
        
        //cek validasi
        if (txtTugas.getText().isEmpty()) {
            tugas=0;
        }else{
            tugas=Integer.parseInt(txtTugas.getText());
        }
        if(txtUTS.getText().isEmpty()){
            uts=0;
        }else{
            uts=Integer.parseInt(txtUTS.getText());
        }
        if(txtUAS.getText().isEmpty()){
            uas=0;
        }else{
            uas=Integer.parseInt(txtUAS.getText());
        }
        akhir=(0.2*tugas)+(0.3*uts)+(0.5*uas);
        txtAkhir.setText(String.valueOf(akhir));
        if (akhir>=85) {
            huruf="A";
        }else if(akhir>=80){
            huruf="AB";
        }else if(akhir>=70){
            huruf="B";
        }else if(akhir>=65){
            huruf="BC";
        }else if(akhir>=60){
            huruf="C";
        }else if(akhir>=50){
            huruf="D";
        }else{
            huruf="E";
        }
        txtHuruf.setText(huruf);
        btnTambah.setEnabled(true);
    }//GEN-LAST:event_txtUASFocusLost

    private void txtNIMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNIMFocusLost
        String nmprogdi = null, progdi = txtNIM.getText().substring(0,3);
        int pilih;
        if (progdi.equalsIgnoreCase("A22")) {
            nmprogdi="TI - D3";
            pilih=1;
        }else if (progdi.equalsIgnoreCase("A24")) {
            nmprogdi = "Broadcasting - D3";
            pilih = 1;
        }else{
            txtNama.setEnabled(false);
            JOptionPane.showMessageDialog(null, "NIM salah, ulangi ...", "peringatan", 1);
            pilih =0;
            txtNIM.requestFocus();
        }
        if (pilih==1) {
            txtProdi.setText(nmprogdi);
            txtNama.setEnabled(true);
            txtNama.requestFocus();
        }
        btnBersih.setEnabled(true);
        btnBatal.setEnabled(true);
        btnBaru.setEnabled(false);
    }//GEN-LAST:event_txtNIMFocusLost

    private void txtNamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamaFocusLost
        cmbMatkul.setEnabled(true);
    }//GEN-LAST:event_txtNamaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_latih5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_latih5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_latih5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_latih5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_latih5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBersih;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cmbMatkul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelMatkul;
    private javax.swing.JTextField txtAkhir;
    private javax.swing.JTextField txtHuruf;
    private javax.swing.JTextField txtIPS;
    private javax.swing.JTextField txtJenis;
    private javax.swing.JTextField txtNIM;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtProdi;
    private javax.swing.JTextField txtSKS;
    private javax.swing.JTextField txtSkstotal;
    private javax.swing.JTextField txtTugas;
    private javax.swing.JTextField txtUAS;
    private javax.swing.JTextField txtUTS;
    // End of variables declaration//GEN-END:variables
}
