/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbo1a223303;

/**
 *
 * @author Wildan
 */
public class FrmTugas01 extends javax.swing.JFrame {
    String bil="";
    double jumlah,bil1,bil2;
    int pilih;
    /**
     * Creates new form FrmTugas01
     */
    public FrmTugas01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtlayar = new javax.swing.JTextField();
        txt1 = new javax.swing.JButton();
        txt2 = new javax.swing.JButton();
        txt3 = new javax.swing.JButton();
        txt4 = new javax.swing.JButton();
        txt5 = new javax.swing.JButton();
        txt6 = new javax.swing.JButton();
        txt7 = new javax.swing.JButton();
        txt8 = new javax.swing.JButton();
        txt9 = new javax.swing.JButton();
        txtClr = new javax.swing.JButton();
        txt0 = new javax.swing.JButton();
        txtKoma = new javax.swing.JButton();
        txtTambah = new javax.swing.JButton();
        txtKurang = new javax.swing.JButton();
        txtKali = new javax.swing.JButton();
        txtBagi = new javax.swing.JButton();
        txtKuadrat = new javax.swing.JButton();
        txtPangkat = new javax.swing.JButton();
        txtAkar = new javax.swing.JButton();
        txtJumlah = new javax.swing.JButton();
        txtAkarkubik = new javax.swing.JButton();
        txtSin = new javax.swing.JButton();
        txtCos = new javax.swing.JButton();
        txtTan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txt1.setText("1");
        txt1.setPreferredSize(new java.awt.Dimension(60, 60));
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });

        txt2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txt2.setText("2");
        txt2.setPreferredSize(new java.awt.Dimension(60, 60));
        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });

        txt3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txt3.setText("3");
        txt3.setPreferredSize(new java.awt.Dimension(60, 60));
        txt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt3ActionPerformed(evt);
            }
        });

        txt4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txt4.setText("4");
        txt4.setPreferredSize(new java.awt.Dimension(60, 60));
        txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt4ActionPerformed(evt);
            }
        });

        txt5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txt5.setText("5");
        txt5.setPreferredSize(new java.awt.Dimension(60, 60));
        txt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt5ActionPerformed(evt);
            }
        });

        txt6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txt6.setText("6");
        txt6.setPreferredSize(new java.awt.Dimension(60, 60));
        txt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt6ActionPerformed(evt);
            }
        });

        txt7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txt7.setText("7");
        txt7.setPreferredSize(new java.awt.Dimension(60, 60));
        txt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt7ActionPerformed(evt);
            }
        });

        txt8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txt8.setText("9");
        txt8.setPreferredSize(new java.awt.Dimension(60, 60));
        txt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt8ActionPerformed(evt);
            }
        });

        txt9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txt9.setText("8");
        txt9.setPreferredSize(new java.awt.Dimension(60, 60));
        txt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt9ActionPerformed(evt);
            }
        });

        txtClr.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtClr.setText("c");
        txtClr.setPreferredSize(new java.awt.Dimension(60, 60));
        txtClr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClrActionPerformed(evt);
            }
        });

        txt0.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txt0.setText("0");
        txt0.setPreferredSize(new java.awt.Dimension(60, 60));
        txt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt0ActionPerformed(evt);
            }
        });

        txtKoma.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtKoma.setText(".");
        txtKoma.setPreferredSize(new java.awt.Dimension(60, 60));
        txtKoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKomaActionPerformed(evt);
            }
        });

        txtTambah.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtTambah.setText("+");
        txtTambah.setPreferredSize(new java.awt.Dimension(60, 60));
        txtTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTambahActionPerformed(evt);
            }
        });

        txtKurang.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtKurang.setText("-");
        txtKurang.setPreferredSize(new java.awt.Dimension(60, 60));
        txtKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKurangActionPerformed(evt);
            }
        });

        txtKali.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtKali.setText("X");
        txtKali.setPreferredSize(new java.awt.Dimension(60, 60));
        txtKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKaliActionPerformed(evt);
            }
        });

        txtBagi.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtBagi.setText("/");
        txtBagi.setPreferredSize(new java.awt.Dimension(60, 60));
        txtBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBagiActionPerformed(evt);
            }
        });

        txtKuadrat.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtKuadrat.setText("X²");
        txtKuadrat.setPreferredSize(new java.awt.Dimension(60, 60));
        txtKuadrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKuadratActionPerformed(evt);
            }
        });

        txtPangkat.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtPangkat.setText("Xˆ");
        txtPangkat.setPreferredSize(new java.awt.Dimension(60, 60));
        txtPangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPangkatActionPerformed(evt);
            }
        });

        txtAkar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtAkar.setText("√");
        txtAkar.setPreferredSize(new java.awt.Dimension(60, 60));
        txtAkar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAkarActionPerformed(evt);
            }
        });

        txtJumlah.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtJumlah.setText("=");
        txtJumlah.setPreferredSize(new java.awt.Dimension(60, 60));
        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });

        txtAkarkubik.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtAkarkubik.setText("³√");
        txtAkarkubik.setPreferredSize(new java.awt.Dimension(60, 60));
        txtAkarkubik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAkarkubikActionPerformed(evt);
            }
        });

        txtSin.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtSin.setText("Sin");
        txtSin.setPreferredSize(new java.awt.Dimension(60, 60));
        txtSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSinActionPerformed(evt);
            }
        });

        txtCos.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtCos.setText("Cos");
        txtCos.setPreferredSize(new java.awt.Dimension(60, 60));
        txtCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCosActionPerformed(evt);
            }
        });

        txtTan.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtTan.setText("Tan");
        txtTan.setPreferredSize(new java.awt.Dimension(60, 60));
        txtTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtClr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(66, 66, 66)
                                                .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txt0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtKoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(6, 6, 6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKurang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBagi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtKuadrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPangkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAkar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAkarkubik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtlayar, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(txtlayar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKuadrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPangkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAkar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAkarkubik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKurang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBagi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
        switch(pilih){
            case 1 : 
            bil2=Double.parseDouble(String.valueOf(txtlayar.getText()));
            jumlah = bil1+bil2;
            bil=Double.toString(jumlah);
            break;
            case 2 : 
            bil2=Double.parseDouble(String.valueOf(txtlayar.getText()));
            jumlah = bil1 - bil2;
            bil=Double.toString(jumlah);
            break;
            case 3 : 
            bil2=Double.parseDouble(String.valueOf(txtlayar.getText()));
            jumlah = bil1 * bil2;
            bil=Double.toString(jumlah);
            break;
            case 4 : 
            bil2=Double.parseDouble(String.valueOf(txtlayar.getText()));
            jumlah = bil1 / bil2;
            bil=Double.toString(jumlah);
            break;
            case 5 :
            int y=1,jml;    
            bil2=Double.parseDouble(bil);
            for (jml=1; jml<=bil2; jml++){
                y= (int) (bil1 * y);
            }
            jumlah=y;
            bil=Double.toString(jumlah);
            case 6:
            bil2=Double.parseDouble(bil);
            jumlah=Math.sin(bil2);
            bil=Double.toString(jumlah);
            case 7:
            bil2=Double.parseDouble(bil);
            jumlah=Math.cos(bil2);
            bil=Double.toString(jumlah);
            case 8:
            bil2=Double.parseDouble(bil);
            jumlah=Math.tan(bil2);
            bil=Double.toString(jumlah);
        }
                     
        txtlayar.setText(bil);                         
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
        bil +="1";
        txtlayar.setText(bil);
    }//GEN-LAST:event_txt1ActionPerformed

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
        bil +="2";
        txtlayar.setText(bil);
    }//GEN-LAST:event_txt2ActionPerformed

    private void txt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt3ActionPerformed
        // TODO add your handling code here:
        bil +="3";
        txtlayar.setText(bil);
    }//GEN-LAST:event_txt3ActionPerformed

    private void txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt4ActionPerformed
        // TODO add your handling code here:
        bil +="4";
        txtlayar.setText(bil);
    }//GEN-LAST:event_txt4ActionPerformed

    private void txt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt5ActionPerformed
        // TODO add your handling code here:
        bil +="5";
        txtlayar.setText(bil);
    }//GEN-LAST:event_txt5ActionPerformed

    private void txt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt6ActionPerformed
        // TODO add your handling code here:
        bil +="6";
        txtlayar.setText(bil);
    }//GEN-LAST:event_txt6ActionPerformed

    private void txt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt7ActionPerformed
        // TODO add your handling code here:
        bil +="7";
        txtlayar.setText(bil);
    }//GEN-LAST:event_txt7ActionPerformed

    private void txt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt9ActionPerformed
        // TODO add your handling code here:
        bil +="8";
        txtlayar.setText(bil);
    }//GEN-LAST:event_txt9ActionPerformed

    private void txt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt8ActionPerformed
        // TODO add your handling code here:
        bil +="9";
        txtlayar.setText(bil);
    }//GEN-LAST:event_txt8ActionPerformed

    private void txt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt0ActionPerformed
        // TODO add your handling code here:
        bil +="0";
        txtlayar.setText(bil);
    }//GEN-LAST:event_txt0ActionPerformed

    private void txtTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTambahActionPerformed
        // TODO add your handling code here:
        bil1 =  Double.parseDouble(bil);
        txtlayar.setText("+");
        bil="";
        pilih=1;
                             
    }//GEN-LAST:event_txtTambahActionPerformed

    private void txtKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKurangActionPerformed
        // TODO add your handling code here:
        bil1 =  Double.parseDouble(bil);
        txtlayar.setText("-");
        bil="";
        pilih=2;
    }//GEN-LAST:event_txtKurangActionPerformed

    private void txtKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKaliActionPerformed
        // TODO add your handling code here:
        bil1 =  Double.parseDouble(bil);
        txtlayar.setText("x");
        bil="";
        pilih=3;
    }//GEN-LAST:event_txtKaliActionPerformed

    private void txtBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBagiActionPerformed
        // TODO add your handling code here:
        bil1 =  Double.parseDouble(bil);
        txtlayar.setText("/");
        bil="";
        pilih=4;
    }//GEN-LAST:event_txtBagiActionPerformed

    private void txtKomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKomaActionPerformed
        // TODO add your handling code here:
        bil +=".";
        txtlayar.setText(bil);
    }//GEN-LAST:event_txtKomaActionPerformed

    private void txtClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClrActionPerformed
        // TODO add your handling code here:
        txtlayar.setText(null);
        bil1=0.0;
        bil2=0.0;
        jumlah=0.0;
        bil="";
    }//GEN-LAST:event_txtClrActionPerformed

    private void txtKuadratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKuadratActionPerformed
        // TODO add your handling code here:
        bil1= Double.parseDouble(bil);
        txtlayar.setText("^2");
        bil="";
        jumlah = bil1 * bil1;
        bil=Double.toString(jumlah);
        txtlayar.setText(bil); 
    }//GEN-LAST:event_txtKuadratActionPerformed

    private void txtPangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPangkatActionPerformed
        // TODO add your handling code here:
        bil1=Double.parseDouble(bil);
        txtlayar.setText("^");
        bil="";
        pilih=5;
    }//GEN-LAST:event_txtPangkatActionPerformed

    private void txtAkarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAkarActionPerformed
        // TODO add your handling code here:
        bil1=Double.parseDouble(bil);
        txtlayar.setText("√");
        bil="";
        jumlah=Math.sqrt(bil1);
        bil=Double.toString(jumlah);
        txtlayar.setText(bil);
               
    }//GEN-LAST:event_txtAkarActionPerformed

    private void txtAkarkubikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAkarkubikActionPerformed
        // TODO add your handling code here:
        bil1=Double.parseDouble(bil);
        txtlayar.setText("³√");
        bil="";
        jumlah=Math.cbrt(bil1);
        bil=Double.toString(jumlah);
        txtlayar.setText(bil);
    }//GEN-LAST:event_txtAkarkubikActionPerformed

    private void txtSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSinActionPerformed
        // TODO add your handling code here:
        txtlayar.setText("Sin");
        bil="";
        pilih=6;
        
    }//GEN-LAST:event_txtSinActionPerformed

    private void txtCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCosActionPerformed
        // TODO add your handling code here:
        txtlayar.setText("Cos");
        bil="";
        pilih=7;
    }//GEN-LAST:event_txtCosActionPerformed

    private void txtTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanActionPerformed
        // TODO add your handling code here:
        txtlayar.setText("Tan");
        bil="";
        pilih=8;
    }//GEN-LAST:event_txtTanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTugas01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTugas01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTugas01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTugas01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTugas01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton txt0;
    private javax.swing.JButton txt1;
    private javax.swing.JButton txt2;
    private javax.swing.JButton txt3;
    private javax.swing.JButton txt4;
    private javax.swing.JButton txt5;
    private javax.swing.JButton txt6;
    private javax.swing.JButton txt7;
    private javax.swing.JButton txt8;
    private javax.swing.JButton txt9;
    private javax.swing.JButton txtAkar;
    private javax.swing.JButton txtAkarkubik;
    private javax.swing.JButton txtBagi;
    private javax.swing.JButton txtClr;
    private javax.swing.JButton txtCos;
    private javax.swing.JButton txtJumlah;
    private javax.swing.JButton txtKali;
    private javax.swing.JButton txtKoma;
    private javax.swing.JButton txtKuadrat;
    private javax.swing.JButton txtKurang;
    private javax.swing.JButton txtPangkat;
    private javax.swing.JButton txtSin;
    private javax.swing.JButton txtTambah;
    private javax.swing.JButton txtTan;
    private javax.swing.JTextField txtlayar;
    // End of variables declaration//GEN-END:variables
}
